api:
  build: .
  restart: always
  ports:
    - "9090:9090"
  links:
    - "cache-db:redis"
  environment:
    - CATEGORY_API_REDIS_HOST=redis
    - CATEGORY_API_REDIS_DATABASE=category-api

cache-db:
   image: redis:4.0.1-alpine
   restart: always
   volumes:
    - ./redisdbdata:/data
   command: redis-server --appendonly yes
