api:
  build: .
  restart: always
  ports:
    - "9090:9090"
  links:
    - "cache-db:redis"
  environment:
    - SENSICITY_CATEGORY_REDIS_HOST=redis

cache-db:
   image: redis:3.2.7-alpine
   restart: always
   volumes:
    - ./redisdbdata:/data
   command: redis-server --appendonly yes
